project:
  name: g104_billsum_llama_1b_lora
  task: billsum
  output_root: ../outputs/billsum_llama_1b_lora

data:
  train_file: ../billsum data cleaning/output/train_sft.jsonl
  valid_file: ../billsum data cleaning/output/val_sft.jsonl
  test_us_file: ../billsum data cleaning/output/test_us_sft.jsonl
  test_ca_file: ../billsum data cleaning/output/test_ca_sft.jsonl

model_name: meta-llama/Llama-3.2-1B-Instruct
adapter_dir: ../outputs/billsum_llama_1b_lora/adapter

generation:
  max_input_tokens: 16384
  max_new_tokens: 2048
  do_sample: false
  num_beams: 1

evaluation:
  rouge_use_stemmer: true
